# currencies.py
currencies = {
    "eur": "EUR",
    "usd": "USD",
    "jpy": "JPY",
    "gbp": "GBP",
    "chf": "CHF",
    "cad": "CAD",
    "aud": "AUD",
    "nzd": "NZD",
    "cny": "CNY",
    "rub": "RUB",
    "brl": "BRL",
    "inr": "INR",
    "mxn": "MXN",
    "sgd": "SGD",
    "hkd": "HKD",
    "krw": "KRW",
    "try": "TRY",
    "zar": "ZAR",
    "sek": "SEK",
    "nok": "NOK",
}

currency_symbols = {
    "eur": "€",
    "usd": "$",
    "jpy": "¥",
    "gbp": "£",
    "chf": "FR",
    "cad": "$",
    "aud": "$",
    "nzd": "$",
    "cny": "¥",
    "rub": "₽",
    "brl": "R$",
    "inr": "₹",
    "mxn": "$",
    "sgd": "$",
    "hkd": "$",
    "krw": "₩",
    "try": "₺",
    "zar": "R",
    "sek": "kr",
    "nok": "kr",
}

